services:
  app:
    restart: always
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: .env
    ports:
      - "${APACHE_UNSECURE_PORT}:80"
    volumes:
      - ../app:/var/www/html
      - /var/www/html/vendor
      - ./logs:/var/log/sans-log
  mariadb:
    image: mariadb:10.6
    restart: on-failure
    env_file: .env
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - 'sans_data:/var/lib/mysql'
volumes:
  sans_data:
    external: false
